# ros2_control hardware config that loads the ROS2ControlBridge plugin
ros2_control:
  ros__parameters:
    hardware:
      plugin: leremix_control_plugin/ROS2ControlBridge

      # Topics for communication with servo manager
      base_cmd_topic: /motor_manager/base_cmd
      arm_cmd_topic: /motor_manager/arm_cmd
      head_cmd_topic: /motor_manager/head_cmd
      state_topic: /motor_manager/joint_states

      # optional
      publish_if_unchanged: true

    joints:
      # Base joints — velocity command, position+velocity states
      - name: wheel3_rotation
        command_interfaces: [velocity]
        state_interfaces: [position, velocity]
      - name: wheel1_rotation
        command_interfaces: [velocity]
        state_interfaces: [position, velocity]
      - name: wheel2_rotation
        command_interfaces: [velocity]
        state_interfaces: [position, velocity]

      # Arm joints — position command, position state
      - name: "1"
        command_interfaces: [position]
        state_interfaces: [position]
      - name: "2"
        command_interfaces: [position]
        state_interfaces: [position]
      - name: "3"
        command_interfaces: [position]
        state_interfaces: [position]
      - name: "4"
        command_interfaces: [position]
        state_interfaces: [position]
      - name: "5"
        command_interfaces: [position]
        state_interfaces: [position]
      - name: "6"
        command_interfaces: [position]
        state_interfaces: [position]


      - name: camera_tilt
        command_interfaces: [position]
        state_interfaces: [position]
      - name: camera_pan
        command_interfaces: [position]
        state_interfaces: [position]
