[workspace]
channels = ["https://prefix.dev/robostack-jazzy", "https://prefix.dev/conda-forge" ]
name = "LeRemix"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
ros2-distro-mutex = "*"
ros-jazzy-desktop = "*"
ros-jazzy-ros-gz-sim = "*"
ros-jazzy-ros-gz-bridge = "*"
ros-jazzy-ros-gz-image = "*"
ros-jazzy-ros-gz = "*"
ros-jazzy-controller-manager = "*"
ros-jazzy-controller-manager-msgs = "*"
ros-jazzy-ros2-control = "*"
ros-jazzy-ros2-controllers = "*"
ros-jazzy-joint-state-broadcaster = "*"
ros-jazzy-position-controllers = "*"
ros-jazzy-hardware-interface = "*"
ros-jazzy-robot-state-publisher = "*"
ros-jazzy-rclcpp = "*"
ros-jazzy-rclcpp-lifecycle = "*"
ros-jazzy-rclpy  = "*"
ros-jazzy-pluginlib = "*"
ros-jazzy-xacro = "*"
ros-jazzy-launch = "*"
ros-jazzy-launch-ros = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-geometry-msgs = "*"
ros-jazzy-std-msgs = "*"
ros-jazzy-nav-msgs = "*"
ros-jazzy-image-transport = "*"
ros-jazzy-compressed-image-transport = "*"
ros-jazzy-depthimage-to-laserscan = "*"
ros-jazzy-tf2-ros = "*"
ros-jazzy-slam-toolbox = "*"
colcon-common-extensions = "*"
ros-jazzy-ament-cmake-auto = "*"
compilers = "*"
pkg-config = "*"
cmake = "*"
ninja  = "*"
setuptools = "*"
ros-jazzy-gz-ros2-control = "*"
filelock  = "*"
