[workspace]
channels = ["robostack-jazzy", "conda-forge"]
name = "LeRemix"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-jazzy-desktop = ">=0.11.0,<0.12"
ros-jazzy-robot-state-publisher = ">=3.3.3,<4"
ros-jazzy-controller-manager = ">=4.37.0,<5"
ros-jazzy-controller-manager-msgs = ">=4.37.0,<5"
