twist_mux:
  ros__parameters:
    topics:
      xbox:
        topic: cmd_vel_xbox
        timeout: 0.5
        priority: 15
      nav:
        topic: cmd_vel_nav
        timeout: 0.5
        priority: 5
      teleop:
        topic: cmd_vel_teleop
        timeout: 0.5
        priority: 10